MAIN_DIR: '/home/zhangrui/AIC22_Track1_MTMC_ID10'
DET_SOURCE_DIR: 'datasets/AIC22_Track1_MTMC_Tracking/test/S06/images/test/S06'
REID_MODEL: 'models/reid/resnext101_ibn_a_2.pth'
REID_BACKBONE: 'resnext101_ibn_a'
DET_IMG_DIR: 'datasets/test_reproduce/'         # same as DATA_DIR
OUTPUT_DIR: 'datasets/test_reproduce/detect_reid2/'   # dst dir
REID_SIZE_TEST: [384, 384]